<ADCScreenTest>:
    md_bg_color: self.theme_cls.backgroundColor

    MDBoxLayout:
        orientation: 'vertical'
        padding: dp(24)

        MDBoxLayout:
            size_hint_y: None
            height: dp(48)
            radius: 7
            pos_hint: {'top': 1}
            spacing: dp(48)
            Widget:
                size_hint_x: .1
            NavBtn:
                id: adc_btn
                text: 'ADC'
                height: dp(48)
            NavBtn:
                id: mcp_btn
                text: 'MCP'
                height: dp(48)
            Widget:
                size_hint_x: .1

        MDBoxLayout:
            orientation: 'vertical'
            padding: dp(0), dp(48), dp(0), dp(48)
            MDRelativeLayout:
                MDGridLayout:
                    cols: 2
                    spacing: dp(42)
                    padding: (dp(125), dp(0), dp(125), dp(0))
                    adaptive_height: True
                    pos_hint: {'center_x': .5, 'center_y': .5}

                    ValueField:
                        text: str(round(request_slider.value))
                        icon: 'transfer-up'
                        field: 'Requests'
                        on_text: request_slider.value = min(max(int(self.text), 1), 1000) if self.text.isdigit() else 0
                    MDSlider:
                        id: request_slider
                        range: (1, 1000)
                        MDSliderHandle:
                        MDSliderValueLabel:

                    ValueField:
                        text: str(round(frequency_slider.value))
                        icon: 'timer-refresh'
                        field: 'Frequency'
                        on_text: frequency_slider.value = min(max(int(self.text), 1), 60) if self.text.isdigit() else 0
                    MDSlider:
                        id: frequency_slider
                        range: (1, 60)
                        MDSliderHandle:
                        MDSliderValueLabel:

                    ValueField:
                        text: str(round(stored_slider.value))
                        icon: 'folder-download'
                        field: 'Stored'
                        on_text: stored_slider.value = min(max(int(self.text), 1), 2000) if self.text.isdigit() else 0
                    MDSlider:
                        id: stored_slider
                        range: (1, 2000)
                        MDSliderHandle:
                        MDSliderValueLabel:
        MDBoxLayout:
            size_hint_y: None
            height: dp(48)
            pos_hint: {'bottom': 1}
            padding: dp(250), dp(0)
            MDButton:
                style: 'elevated'
                theme_width: 'Custom'
                size_hint_y: None
                height: dp(48)
                size_hint_x: 1
                radius: 7
                MDButtonText:
                    text: 'START'
                    font_style: 'Title'
                    role: 'large'
                    pos_hint: {'center_x': .5, 'center_y': .5}


<NavBtn@MDButton>:
    text: ''
    style: 'elevated'
    theme_width: 'Custom'
    size_hint_y: None
    radius: 0
    MDButtonText:
        text: root.text
        font_style: 'Headline'
        role: 'small'
        pos_hint: {'center_x': .5, 'center_y': .5}

<ValueField@MDTextField>:
    text: ''
    icon: ''
    field: ''
    hint: ''
    mode: 'outlined'
    theme_text_color: 'Custom'
    text_color_normal: '#F7F7F7'
    halign: 'center'
    size_hint_x: .3
    MDTextFieldHintText:
        text: root.field
    MDTextFieldHelperText:
        text: root.hint
        mode: 'persistent'
    MDTextFieldTrailingIcon:
        icon: root.icon