<MCPTestScreen>:
    id: mcp_test_screen
    md_bg_color: self.theme_cls.backgroundColor

    MDBoxLayout:
        orientation: 'vertical'
        padding: dp(12)

        MDBoxLayout:
            size_hint_y: None
            height: dp(48)
            radius: 7
            pos_hint: {'top': 1}
            spacing: dp(42)
            Widget:
                size_hint_x: .1
            NavBtn:
                id: adc_btn
                text: 'ADC'
                height: dp(48)
                size_hint_x: .4
                on_press: app.switch_screen('adc_test_screen')
            NavBtn:
                id: mcp_btn
                text: 'MCP'
                height: dp(48)
                size_hint_x: .4
                disabled: True
            Widget:
                size_hint_x: .1
    
        MDBoxLayout:
            orientation: 'vertical'
            padding: dp(0), dp(0), dp(0), dp(0)
            MDRelativeLayout:
                MDGridLayout:
                    cols: 2
                    spacing: dp(24)
                    padding: (dp(125), dp(0), dp(125), dp(0))
                    adaptive_height: True
                    pos_hint: {'center_x': .5, 'center_y': .5}

                    ValueField:
                        text: str(round(mcp_delay.value))
                        icon: 'timer-refresh'
                        field: 'Cycle Delay (seconds)'
                        on_text: mcp_cycle_delay.value = min(max(int(self.text), 1), 120) if self.text.isdigit() else 0
                    MDSlider:
                        id: mcp_cycle_delay
                        range: (1, 120)
                        MDSliderHandle:
                        MDSliderValueLabel:

                    ValueField:
                        text: str(round(mcp_delay.value))
                        icon: 'timer-refresh'
                        field: 'Pin Delay (milliseconds)'
                        on_text: mcp_pin_delay.value = min(max(int(self.text), 1), 1000) if self.text.isdigit() else 0
                    MDSlider:
                        id: mcp_pin_delay
                        range: (1, 1000)
                        MDSliderHandle:
                        MDSliderValueLabel:

                MDGridLayout:
                    cols: 2
                    spacing: dp(24)
                    padding: (dp(125), dp(0), dp(125), dp(0))
                    adaptive_height: True
                    pos_hint: {'center_x': .5, 'center_y': .5}

                    MDButton:
                        style: 'elevated'
                        theme_width: 'Custom'
                        size_hint_y: None
                        height: dp(48)
                        size_hint_x: 1
                        radius: 7
                        on_press: mcp_test_screen.start_run_cycle(mcp_cycle_delay.value, mcp_pin_delay.value)
                        MDButtonText:
                            text: 'Run Cycle'
                            font_style: 'Title'
                            role: 'large'
                            pos_hint: {'center_x': .5, 'center_y': .5}

                    MDButton:
                        style: 'elevated'
                        theme_width: 'Custom'
                        size_hint_y: None
                        height: dp(48)
                        size_hint_x: 1
                        radius: 7
                        on_press: mcp_test_screen.start_functionality_test(mcp_delay.value, mcp_pin_delay.value)
                        MDButtonText:
                            text: 'Functionality Test'
                            font_style: 'Title'
                            role: 'large'
                            pos_hint: {'center_x': .5, 'center_y': .5}